# Symbol that prefixes all network chat.
# To change it to the server that it is coming from, set it to '' (with the quotes!) and change your Herochat default format.
# Mine looks like this:
# default: '&a[S]{color}[{nick}] {prefix}{sender}{suffix}{color}: {msg}'
# I added the &a[S] at the start on my survival server which will prefix all messages from that server with &a[S]. On my creative server it is set to &a[C].]
prefix-symbol: [N]